[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Uncomment to enable basic password protection
# [[redirects]]
#   from = "/*"
#   to = "/.netlify/functions/auth"
#   status = 200
#   force = true
#   conditions = {Role = ["admin"]}
